### ISSUE TITLE
安装失败，安卓11，miui12.5，红米k20pro

### ISSUE THREAD

**Issue by RiXiangXiaMei** [GSWXXN/RestoreSplashScreen#2]
INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1009619353.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #31 (current version is #30)
![Screenshot_2022-05-02-09-43-28-447_com.yxer.packageinstalles.jpg](https://user-images.githubusercontent.com/73896345/166174922-ce42adc8-e06f-4acb-bd58-d501fcf2a7c7.jpg)

**Comment by GSWXXN** [comment]
检查自己的安卓版本，这是给安卓12用的模块。报错信息很明确了
