### ISSUE TITLE
在QPR1上导致system ui重启

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [GSWXXN/RestoreSplashScreen#23]
问题描述：
我有三个设备，都运行着Android 13 QPR1 类原生（一月补丁）与MIUI遮罩进化。而在其中两个设备中，会导致点开一些应用导致system ui崩溃重启。但是在剩下的一个设备中则没有任何问题。
出现问题的系统是：
1. Derpfest unofficial 
2. Lineage OS 20 GSI

没有出现的问题的系统是
1. Cherish OS 4.4

出现的问题的应用似乎并没有共通点，分别有明日方舟，手机性能排行，Notion，欧路词典等等

而在我这两个设备升级到QPR1之前（也同样是类原生），都没有出现任何问题。

**Comment by JaneValleyhasBtaken** [comment]
Log：
[LSPosed_2023-01-25T01_43_35.183455.zip](https://github.com/GSWXXN/RestoreSplashScreen/files/10491018/LSPosed_2023-01-25T01_43_35.183455.zip)

**Comment by JaneValleyhasBtaken** [comment]
Log：
[verbose_2023-01-25T01_43_10.537339.log](https://github.com/GSWXXN/RestoreSplashScreen/files/10491074/verbose_2023-01-25T01_43_10.537339.log)
[modules_2023-01-24T06_28_42.235868.log](https://github.com/GSWXXN/RestoreSplashScreen/files/10491075/modules_2023-01-24T06_28_42.235868.log)

**Comment by JaneValleyhasBtaken** [comment]
Log
[verbose_2023-01-25T01_43_10.537339.log](https://github.com/GSWXXN/RestoreSplashScreen/files/10491083/verbose_2023-01-25T01_43_10.537339.log)

[modules_2023-01-25T01_43_09.066586.log](https://github.com/GSWXXN/RestoreSplashScreen/files/10491082/modules_2023-01-25T01_43_09.066586.log)

**Comment by GSWXXN** [comment]
确实有很多Hook失败的地方, 但是我在 Android Code Search 上并没有找到对应改动. 可以把你的 /system/framework/services.jar 提取出来么

**Comment by JaneValleyhasBtaken** [comment]
行
GitHub传文件有点问题，所以加了个log后缀
[services.jar.log](https://github.com/GSWXXN/RestoreSplashScreen/files/10492103/services.jar.log)

**Comment by GSWXXN** [comment]
再提取一下系统界面呗

**Comment by JaneValleyhasBtaken** [comment]
嗯

https://we.tl/t-03mWauHYB7

**Comment by GSWXXN** [comment]
看过文件了, 类似情况之前也有人向我反馈过, 你可以看下[此前的讨论](https://www.coolapk.com/feed/41945385?shareKey=OTJkMTMxN2IzNmYwNjNkMDQwNjc~&shareUid=1189245&shareFrom=com.coolapk.market_12.5.3), 不过我目前也没有解决办法 :-(

**Comment by GSWXXN** [comment]
已完成对 SystemUI Hook 的重构, 模块应该可以在更多系统上运行了
测试系统: [Lineage OS 20 GSI](https://sourceforge.net/projects/andyyan-gsi/files/lineage-20-td/)

请到 [Actions](https://github.com/GSWXXN/RestoreSplashScreen/actions/runs/6045275762) 中下载测试

**Comment by JaneValleyhasBtaken** [comment]
辛苦了 我这就去试试
