### ISSUE TITLE
图标灰边遮罩

### ISSUE THREAD

**Issue by iTeraxo** [GSWXXN/RestoreSplashScreen#29]
![Screenshot_2023-09-18-13-16-30-245_com coolapk market](https://github.com/GSWXXN/RestoreSplashScreen/assets/104311389/61279d9e-6ed9-4e30-9c06-0c5eb25de739)
之前和您说过😄有思路解决了吗？
新版要出了吧😋

**Comment by GSWXXN** [comment]
新版本在某些场景下还有些小问题，离发布正式版应该还要一段时间。

你提的这个问题我已经有思路了，这两天也会着手尝试一下哈

**Comment by natsu1949** [comment]
> 新版本在某些场景下还有些小问题，离发布正式版应该还要一段时间。
> 
> 你提的这个问题我已经有思路了，这两天也会着手尝试一下哈

好耶☺️

**Comment by GSWXXN** [comment]
抱歉回复晚了, 之前的想法可能不正确. 现在暂时还是没有有效的方法或思路去除这个灰边. :-(
~最近时间又不多了, 可能又要拖一拖~

**Comment by GSWXXN** [comment]
虽然还是没有找到直接原因, 但是我重构了可能间接导致灰边被添加的功能, 你可以下载最新 CI 版测试一下, 在 Github 网页版的Actions 里

**Comment by natsu1949** [comment]
> 虽然还是没有找到直接原因, 但是我重构了可能间接导致灰边被添加的功能, 你可以下载最新 CI 版测试一下, 在 Github 网页版的Actions 里

白色背景的已经解决👍，其他颜色的没有改变
![Screenshot_2023-11-17-14-20-12-110_com fankes miui notify](https://github.com/GSWXXN/RestoreSplashScreen/assets/104311389/ee53301c-c03c-42cb-ab9f-694b48ab9bc5)

**Comment by natsu1949** [comment]
> 虽然还是没有找到直接原因, 但是我重构了可能间接导致灰边被添加的功能, 你可以下载最新 CI 版测试一下, 在 Github 网页版的Actions 里

我突然想起来是这几个图标主题没适配😵这样看来问题已经解决了
