### ISSUE TITLE

支持第三方图标设置

### ISSUE THREAD

**Issue by MartinVon1021** [GSWXXN/RestoreSplashScreen#3]
能否支持第三方图标包？

**Comment by GSWXXN** [comment]
在开发模块的初期我是有这个想法的，但是“替换获取图标方式”这个功能出来后遮罩图标已经可以随着主题图标变化了，所以后来我也没再想过支持图标包。我想问你一下，有什么场景需要使用图标包，开发这个功能的意义大么？

**Comment by MartinVon1021** [comment]
第三方桌面用的都是图标包，没有用主题

**Comment by GSWXXN** [comment]
https://github.com/GSWXXN/RestoreSplashScreen/commit/ae72388b9d656bd4be599bfa26e5b6db20b2acd1

**Comment by GSWXXN** [comment]
v1.7包含此功能并已发布，可在LSPosed仓库和酷安下载更新
