### ISSUE TITLE
MIUI14 Android14表现异常

### ISSUE THREAD

**Issue by naicfeng** [GSWXXN/RestoreSplashScreen#31]
首先是配置文件写入了应用目录，而不是misc目录，导致被hook的应用获取不到配置。可能是api的问题？(XSharedPreferences)
然后手动把配置文件复制过去，可以读取配置，但是缩小图标无效了，一直是大图标。

systemui.apk是这个
[MiuiSystemUI_20230316.0.zip](https://github.com/fankes/MIUINativeNotifyIcon/files/12837973/MiuiSystemUI_20230316.0.zip)

**Comment by GSWXXN** [comment]
我现在还没用上 Android 14，模块使用的底层依赖可能也没有对 Android 14进行很好的支持，所以近期我并不会把侧重点放在适配 14 上。

不过你可以在模块基础设置中开启日志，并确保应用配置在正确的目录文件中更改并生效后，重现一下问题，然后把lsp的日志提取出来给我看一下。如果这是一个在日志中能被明显体现出来的问题，我会尝试去修复的

**Comment by naicfeng** [comment]
看起来 New XSharedPreferences 的问题是a14的普遍问题了，[YukiHookAPI](https://github.com/HighCapable/YukiHookAPI) 计划 [2.0](https://highcapable.github.io/YukiHookAPI/zh-cn/guide/supportive.html) 才支持 [Modern Xposed API](https://github.com/libxposed)。（未解决的问题 [yukihookprefsbridge](https://highcapable.github.io/YukiHookAPI/zh-cn/about/future.html#yukihookprefsbridge)）

https://github.com/HighCapable/YukiHookAPI/issues/50#issuecomment-1752282494

lsposed的日志
[verbose_2023-10-09T11_03_17.213976.log](https://github.com/GSWXXN/RestoreSplashScreen/files/12842444/verbose_2023-10-09T11_03_17.213976.log)

**Comment by naicfeng** [comment]
上面的日志看起来没有有效内容，这是新的，有RestoreSplashScreen输出

[verbose_2023-10-09T11_12_58.715187.log](https://github.com/GSWXXN/RestoreSplashScreen/files/12842456/verbose_2023-10-09T11_12_58.715187.log)

[modules_2023-10-09T11_12_58.716154.log](https://github.com/GSWXXN/RestoreSplashScreen/files/12842461/modules_2023-10-09T11_12_58.716154.log)

**Comment by GSWXXN** [comment]
试着修了一下图标不能缩小的问题, 你可以试试最新 CI 版本

**Comment by GSWXXN** [comment]
XSharedPreferences 在安卓 14 上的问题不应该是我去解决, 还是等等 YukiHookAPI 的 Modern Xposed API 进度吧, 如果我用上了安卓 14 这个问题还没被解决的话, 我可能考虑在模块内做一个临时的解决方案

**Comment by naicfeng** [comment]
https://github.com/GSWXXN/RestoreSplashScreen/commit/88e4b921e159afaa45097bc8703528777bc62b8a 的ci无法在14上运行，因为 YukiHookAPI 1.1.11 不支持 14 https://github.com/HighCapable/YukiHookAPI/issues/43

targetSdk 改为 33 后，自编译运行良好

**Comment by naicfeng** [comment]
XSharedPreferences 已经修了 https://github.com/LSPosed/LSPosed/commit/159a3adcf8e0832a3e45dccedbb54767dd9f7c4d
