### ISSUE TITLE
Android 14 HyperOS 启动即崩溃

### ISSUE THREAD

**Issue by YuKongA** [GSWXXN/RestoreSplashScreen#32]
小米14 
OS1.0.11.0

[data_app_crash@1698799658091.txt](https://github.com/GSWXXN/RestoreSplashScreen/files/13222368/data_app_crash%401698799658091.txt)

**Comment by GSWXXN** [comment]
模块使用的旧版依赖在 android 14 上会引起这个问题, 现在已将依赖升级至新版, 请到 Actions 下载最新 CI 版测试哈

**Comment by YuKongA** [comment]
好的，能用了
