### ISSUE TITLE
在澎湃 OS 上切换深色模式导致 System UI 重启

### ISSUE THREAD

**Issue by cxzlw** [GSWXXN/RestoreSplashScreen#33]
如题，日志我看看咋上传

**Comment by cxzlw** [comment]
https://1drv.ms/u/s!AnM9HlY-IOtPhhTarCcEscQpY_Cn

**Comment by GSWXXN** [comment]
你在使用2.7.3版本的模块吗，如果是的话请尝试用最新 CI 版，在 GitHub 网页版 的 Actions下

**Comment by cxzlw** [comment]
> 你在使用2.7.3版本的模块吗，如果是的话请尝试用最新 CI 版，在 GitHub 网页版 的 Actions下

啊，ci版可以，谢谢大佬awa

**Comment by GSWXXN** [comment]
如果可以的话，能不能再发一下日志呢，我还没用上澎湃os，我想看一下现在有没有什么潜在异常

**Comment by cxzlw** [comment]
> 如果可以的话，能不能再发一下日志呢，我还没用上澎湃os，我想看一下现在有没有什么潜在异常

https://1drv.ms/u/s!AnM9HlY-IOtPhhU6rfz2az-02-IU
好的

**Comment by cxzlw** [comment]
> > 如果可以的话，能不能再发一下日志呢，我还没用上澎湃os，我想看一下现在有没有什么潜在异常
> 
> https://1drv.ms/u/s!AnM9HlY-IOtPhhU6rfz2az-02-IU
> 好的

k60开发版已经推了，咱解了bl也收到了

**Comment by GSWXXN** [comment]
感谢 看日志的话 没发现有其他的异常
