### ISSUE TITLE
替换图标获取方式在澎湃上有问题

### ISSUE THREAD

**Issue by Zori9527** [GSWXXN/RestoreSplashScreen#35]
![Screenshot_2023-12-14-23-10-15-608_com tencent mobileqq](https://github.com/GSWXXN/RestoreSplashScreen/assets/90077841/49380a65-c8cd-4933-876d-9976374760dd)
如图，最新版的CI版本，使用了一个带有分层图标的主题后，部分APP的启动遮罩图标，只会获取前景层，背景不见了；换非分层图标的主题会恢复正常，在MIUI上未出现过类似问题，更新到澎湃后出现的

**Comment by GSWXXN** [comment]
已知问题, 是从此提交 938ce75ce5b8472f998e4c2707379edd6ea48ce6 产生的, 暂时没时间修, 你可以先使用前一个自动构建版本

**Comment by GSWXXN** [comment]
请问一下你使用的是什么主题, 我最近开始想修这个问题, 但是我复现不出来了 :-(

**Comment by Zori9527** [comment]
主题商店里的边际

**Comment by YuKongA** [comment]
试了一下，似乎所有背景是纯净白底的，都会被忽略渲染

**Comment by YuKongA** [comment]
> 试了一下，似乎所有背景是纯净白底的，都会被忽略渲染

开启缩小图标的情况下，模糊的背景里是正常存在图标背景的

**Comment by GSWXXN** [comment]
已修复, 这里简单解释一下问题出现的原因:

去除图标白色背景其实是安卓**原有**的逻辑, [源码在这](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/libs/WindowManager/Shell/src/com/android/wm/shell/startingsurface/SplashscreenContentDrawer.java;l=465-518?q=mIsBgComplex)

在 https://github.com/GSWXXN/RestoreSplashScreen/commit/938ce75ce5b8472f998e4c2707379edd6ea48ce6 这个提交之前, 模块绘制图标圆角是通过把 Drawable 转成 Bitmap, 再用 Canvas 绘制圆角, 最后转成 BitmapDrawable
在这个提交之后, 圆角是通过 View 的轮廓裁剪实现的

可以在上面提到的安卓源码中开头发现
```kotlin
private boolean processAdaptiveIcon(Drawable iconDrawable) {
  if (!(iconDrawable instanceof AdaptiveIconDrawable)) {
     return false;
  }
......
}
```
模块此前绘制圆角逻辑的 BitmapDrawable 是不会完整运行这个函数的
模块新的绘制圆角逻辑保留了图标原始的类型, 即是 AdaptiveIconDrawable 类型的图标可完整运行上述的函数

```kotlin
private boolean processAdaptiveIcon(Drawable iconDrawable) {
.........
      // Only draw the foreground of AdaptiveIcon to the splash screen if below condition
      // meet:
      // A. The background of the adaptive icon is not complicated. If it is complicated,
      // it may contain some information, and
      // B. The background of the adaptive icon is similar to the theme color, or
      // C. The background of the adaptive icon is grayscale, and the foreground of the
      // adaptive icon forms a certain contrast with the theme color.
      // D. Didn't specify icon background color.
      if (!iconColor.mIsBgComplex && mTmpAttrs.mIconBgColor == Color.TRANSPARENT
              && (isRgbSimilarInHsv(mThemeColor, iconColor.mBgColor)
                      || (iconColor.mIsBgGrayscale
                              && !isRgbSimilarInHsv(mThemeColor, iconColor.mFgColor)))) {
...........
}
```
图标背景被去除的情况是这里的条件 A
解决办法就是强制使所有图标的 `mIsBgComplex` 为 true

如果对这个解决办法有任何疑问, 或对这个情况有任何优化建议, 请随时回复
