### ISSUE TITLE
图标获取方式 自定义列表

### ISSUE THREAD

**Issue by Arlene947** [GSWXXN/RestoreSplashScreen#37]
Miui14.05 k50u 遮罩3.0
<img src="https://github.com/GSWXXN/RestoreSplashScreen/assets/128675053/3d6da87e-4e7e-489b-be56-f90196640d99" width=33%>     <img src="https://github.com/GSWXXN/RestoreSplashScreen/assets/128675053/d55112db-ac35-4aa8-90e7-7a42caabeebe" width=33%>  

开启获取跟随主题 大量app会出现角标白边(忽略主动也无法解决)  关闭则不会

**Comment by GSWXXN** [comment]
你的其他位置的图标，比如模块内的应用选择列表的图标会有白边吗![Screenshot_2024-01-06-21-45-24-093_com.gswxxn.restoresplashscreen.jpg](https://github.com/GSWXXN/RestoreSplashScreen/assets/34705923/834ca9c8-d302-428a-b8cb-1f9d1155cb4a)

**Comment by Arlene947** [comment]
> 你的其他位置的图标，比如模块内的应用选择列表的图标会有白边吗![Screenshot_2024-01-06-21-45-24-093_com.gswxxn.restoresplashscreen.jpg](https://github.com/GSWXXN/RestoreSplashScreen/assets/34705923/834ca9c8-d302-428a-b8cb-1f9d1155cb4a)
> 
> 

![Screenshot_2024-01-07-12-29-54-946_com.lemurbrowser.exts.jpg](https://github.com/GSWXXN/RestoreSplashScreen/assets/128675053/fde5205c-26b2-4e36-95e0-550f3a804148)

会 连通知栏的图标也会出现角标

**Comment by GSWXXN** [comment]
开启 替换获取图标方式 后, 模块就会调用系统接口来获取图标, 如果你在其他位置也有类似情况, 那这并不是模块的问题

你可以尝试换个主题图标, 如果还是不能解决那可能就是系统的问题, 需要换个系统版本解决?
