### ISSUE TITLE
澎湃遮罩大方块问题

### ISSUE THREAD

**Issue by vay1314** [GSWXXN/RestoreSplashScreen#38]
您好，最近更新澎湃了，把遮罩模块更新到最新的ci版本了。但还是很多应用都是大方块，按常见问题设置自定义作用域排除，加到忽略应用主动设置，都没解决问题，麻烦作者看看，lsp日志上传 @GSWXXN 
[LSPosed_2024-01-07T07_52_57.631228.zip](https://github.com/GSWXXN/RestoreSplashScreen/files/13851702/LSPosed_2024-01-07T07_52_57.631228.zip)
![Screenshot_2024-01-07-07-51-59-320_com android browser](https://github.com/GSWXXN/RestoreSplashScreen/assets/22141920/e8d3803f-afae-4514-8f38-efa56ecd64df)
![Screenshot_2024-01-07-07-52-07-184_com android contacts](https://github.com/GSWXXN/RestoreSplashScreen/assets/22141920/2fb9f32f-df16-42a9-bb09-e29e7afe08e9)

**Comment by GSWXXN** [comment]
有没有开启 图标 - 绘制图标圆角 呢

**Comment by vay1314** [comment]
> 有没有开启 图标 - 绘制图标圆角 呢

谢谢，😅没有开启，开启后变正常了。之前版本有这开关嘛，升级澎湃后才发现大方块的。

**Comment by GSWXXN** [comment]
很久之前就有这个开关了，只不过之前是默认开启的，某个版本之后改成默认关闭了，因为有的图标不需要绘制圆角，如果一律绘制圆角的话可能会造成不必要的资源消耗

**Comment by vay1314** [comment]
> 很久之前就有这个开关了，只不过之前是默认开启的，某个版本之后改成默认关闭了，因为有的图标不需要绘制圆角，如果一律绘制圆角的话可能会造成不必要的资源消耗

噢，是这样啊。我说我之前没记得打开过这个开关。这次更新后发现有些是圆角有些是大方块，还以为是模块问题了。
