### ISSUE TITLE
配置应用列表能隐藏系统应用

### ISSUE THREAD

**Issue by troublewind** [GSWXXN/RestoreSplashScreen#4]
希望加上这个选项，系统应用几乎没必要用遮罩，列表太多勾起来很麻烦

**Comment by GSWXXN** [comment]
https://github.com/GSWXXN/RestoreSplashScreen/commit/206e6da6b50019cb612411c862963f82d7eb15b1

**Comment by GSWXXN** [comment]
v1.7包含此功能并已发布，可在LSPosed仓库和酷安下载更新
