### ISSUE TITLE
图标周围有黑色色块

### ISSUE THREAD

**Issue by jxf1997** [GSWXXN/RestoreSplashScreen#42]
升级hyperOS2后，图标周围有黑色色块，关闭显示图标以后图标位置会直接变成黑色方块
[LSPosed_2024-11-09T08_26_23.237852.zip](https://github.com/user-attachments/files/17685306/LSPosed_2024-11-09T08_26_23.237852.zip)

**Comment by GSWXXN** [comment]
从日志里看不出有什么明显的异常，由于我没有设备可以升级至 OS2，我没办法在我的设备上做调试
我需要帮忙提取一下下面内容来尝试定位问题
* 出现异常时的屏幕录像
* 出现异常时模块的完整日志（在模块基础设置中打开启用日志即可，出现异常后再把lsp日志提取出来）
* 提取系统界面app

**Comment by jxf1997** [comment]
> 从日志里看不出有什么明显的异常，由于我没有设备可以升级至 OS2，我没办法在我的设备上做调试
> 我需要帮忙提取一下下面内容来尝试定位问题
> * 出现异常时的屏幕录像
> * 出现异常时模块的完整日志（在模块基础设置中打开启用日志即可，出现异常后再把lsp日志提取出来）
> * 提取系统界面app

> > 当时余空已经找出问题了，小米魔改后return 的不一样，小米改成了必须返回分层图标，然后分层图标这个 drawable默认就被绘制成黑色，这种情况能解决嘛？

**Comment by jxf1997** [comment]
> 从日志里看不出有什么明显的异常，由于我没有设备可以升级至 OS2，我没办法在我的设备上做调试
> 我需要帮忙提取一下下面内容来尝试定位问题
> * 出现异常时的屏幕录像
> * 出现异常时模块的完整日志（在模块基础设置中打开启用日志即可，出现异常后再把lsp日志提取出来）
> * 提取系统界面app

![IMG_20241119_154522_166.jpg](https://github.com/user-attachments/assets/b673a84a-4f9c-4138-bdbf-218e47ab8568)

不显示图标时候是这样子的

**Comment by GSWXXN** [comment]
看起来像是把好多个函数合并成一个巨大的函数了, 不太好搞

**Comment by GSWXXN** [comment]
余空在哪里提到过这个问题

**Comment by jxf1997** [comment]
> 余空在哪里提到过这个问题

这个不太清楚，当时在tg群里说的这回事，然后他去找的问题

**Comment by jxf1997** [comment]
> 余空在哪里提到过这个问题

这是当时找到问题时候的链接[https://t.me/c/1903884979/295818]

**Comment by GSWXXN** [comment]
已尝试在 305b98a3d8b79dbd6cfc0bc15da68efffe7dc430 中修复, 请下载最新 CI 版本测试

**Comment by jxf1997** [comment]
> 已尝试在 305b98a3d8b79dbd6cfc0bc15da68efffe7dc430 中修复, 请下载最新 CI 版本测试

嗯，我刚才测试了，已经修复
